### ISSUE TITLE
interrmittent test failure on python3

### ISSUE THREAD

**Issue by rgammans** [rgammans/MysteryMachine#1]
```python
======================================================================
ERROR: testMove (Dlink.DlinkTests)
This behaviour is needed so simpleton UI don't need to much
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/roger/sources/MysteryMachine/py3/tests/Dlink.py", line 113, in testMove
    self.object1["newlink"] = self.object2["link"]
  File "/home/roger/sources/MysteryMachine/py3/MysteryMachine/schema/Locker.py", line 100, in wrapper
    return f(*args,**kwargs)
  File "/home/roger/sources/MysteryMachine/py3/MysteryMachine/schema/MMObject.py", line 162, in __setitem__
    attrobj = self._set_attr_item(attrname,attrvalue)
  File "/home/roger/sources/MysteryMachine/py3/MysteryMachine/schema/Locker.py", line 100, in wrapper
    return f(*args,**kwargs)
  File "/home/roger/sources/MysteryMachine/py3/MysteryMachine/schema/MMAttribute.py", line 66, in _set_attr_item
    attrobj = MMAttribute(attrname,attrvalue,self,complete_write = True)
  File "/home/roger/sources/MysteryMachine/py3/MysteryMachine/schema/MMAttribute.py", line 122, in __init__
    self._complete_write()
  File "/home/roger/sources/MysteryMachine/py3/MysteryMachine/schema/MMAttribute.py", line 221, in _complete_write
    self._compose()
  File "/home/roger/sources/MysteryMachine/py3/MysteryMachine/schema/MMAttribute.py", line 167, in _compose
    self.valueobj._compose(self)
  File "/home/roger/sources/MysteryMachine/py3/MysteryMachine/schema/MMDLinkValue.py", line 465, in _compose
    self.anchordist = _measure_path_diff(obj,self.anchorp)
  File "/home/roger/sources/MysteryMachine/py3/MysteryMachine/schema/MMDLinkValue.py", line 209, in _measure_path_diff
    if f != t: raise RuntimeError('%r is not a parent of %r'%(to,frm))
RuntimeError: dummy:2 is not a parent of dummy:1:newlink

----------------------------------------------------------------------
Ran 220 tests in 495.780s

FAILED (errors=1)
```

**Comment by rgammans** [comment]
My first thogus are to suspect this is timing related because it comes and goes; but there should one be a signle trhead used in this test . It probably something around the TransactionManager; as I think the locks are the only non-deterministic elements that could possible be in involved (there no filesystem in this tests)
